{"uid":"495a0734d839c2e9","name":"An uncaught error was detected outside of a test","fullName":".An uncaught error was detected outside of a test","historyId":"52a12849550d3513996e41b83e83be38","time":{"start":1665866070640,"stop":1665866070764,"duration":124},"description":"","descriptionHtml":"","status":"broken","statusMessage":"The following error originated from your test code, not from Cypress.\n                \n                  > Cannot call `cy.allure()` outside a running test.\n                \n                This usually happens when you accidentally write commands outside an `it(...)` test.\n                \n                If that is the case, just move these commands inside an `it(...)` test.\n                \n                Check your test file for errors.\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.\n                \n                https://on.cypress.io/cannot-execute-commands-outside-test","statusTrace":"CypressError: The following error originated from your test code, not from Cypress.\n                \n                  > Cannot call `cy.allure()` outside a running test.\n                \n                This usually happens when you accidentally write commands outside an `it(...)` test.\n                \n                If that is the case, just move these commands inside an `it(...)` test.\n                \n                Check your test file for errors.\n                \n                When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n                \n                Cypress could not associate this error to any specific test.\n                \n                We dynamically generated a new test to display this failure.\n                \n                https://on.cypress.io/cannot-execute-commands-outside-test\n                    at $Cy.ensureRunnable (https://www.way2automation.com/__cypress/runner/cypress_runner.js:147377:76)\n                    at cy.<computed> [as allure] (https://www.way2automation.com/__cypress/runner/cypress_runner.js:157419:10)\n                    at Object.create (https://www.way2automation.com/__cypress/runner/cypress_runner.js:103421:19)\n                    at context.describe.context.context (https://www.way2automation.com/__cypress/runner/cypress_runner.js:103197:27)\n                    at <unknown> (https://www.way2automation.com/__cypress/runner/cypress_runner.js:162402:21)\n                    at <unknown> (https://www.way2automation.com/__cypress/runner/cypress_runner.js:165463:23)\n                    at tryCatcher (https://www.way2automation.com/__cypress/runner/cypress_runner.js:11318:23)\n                    at Object.gotValue (https://www.way2automation.com/__cypress/runner/cypress_runner.js:10460:18)\n                    at Object.gotAccum (https://www.way2automation.com/__cypress/runner/cypress_runner.js:10449:25)\n                    at Object.tryCatcher (https://www.way2automation.com/__cypress/runner/cypress_runner.js:11318:23)\n                    at Promise._settlePromiseFromHandler (https://www.way2automation.com/__cypress/runner/cypress_runner.js:9253:31)\n                    at Promise._settlePromise (https://www.way2automation.com/__cypress/runner/cypress_runner.js:9310:18)\n                    at Promise._settlePromise0 (https://www.way2automation.com/__cypress/runner/cypress_runner.js:9355:10)\n                    at Promise._settlePromises (https://www.way2automation.com/__cypress/runner/cypress_runner.js:9435:18)\n                    at _drainQueueStep (https://www.way2automation.com/__cypress/runner/cypress_runner.js:6025:12)\n                    at _drainQueue (https://www.way2automation.com/__cypress/runner/cypress_runner.js:6018:9)\n                    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://www.way2automation.com/__cypress/runner/cypress_runner.js:6034:5)\n                    at Async.drainQueues (https://www.way2automation.com/__cypress/runner/cypress_runner.js:5904:14)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"suite","value":""},{"name":"testClass","value":""},{"name":"testMethod","value":"An uncaught error was detected outside of a test"},{"name":"package","value":""},{"name":"resultFormat","value":"allure1"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"495a0734d839c2e9.json","parameterValues":[]}